import type { PortalThemeDefinition, SemanticColorTokens } from './tokens';

/**
 * Customer Portal — public marketing + booking surface.
 * Yellow / black / white. Light canvas; black chrome; yellow CTAs only.
 */
const customerLight: SemanticColorTokens = {
  background: '#FFFFFF',
  foreground: '#0A0A0A',
  surface: '#FFFFFF',
  surfaceForeground: '#0A0A0A',
  surfaceSecondary: '#F4F4F4',
  surfaceSecondaryForeground: '#0A0A0A',
  popover: '#FFFFFF',
  popoverForeground: '#0A0A0A',
  primary: '#F4B400',
  primaryForeground: '#0A0A0A',
  secondary: '#0A0A0A',
  secondaryForeground: '#FFFFFF',
  muted: '#F4F4F4',
  mutedForeground: '#6B7280',
  accent: '#FFD54A',
  accentForeground: '#0A0A0A',
  success: '#059669',
  successForeground: '#FFFFFF',
  warning: '#D97706',
  warningForeground: '#FFFFFF',
  danger: '#DC2626',
  dangerForeground: '#FFFFFF',
  info: '#2563EB',
  infoForeground: '#FFFFFF',
  border: '#E5E5E5',
  input: '#E5E5E5',
  ring: '#F4B400',
  overlay: 'rgb(0 0 0 / 0.55)',
  sidebar: '#0A0A0A',
  sidebarForeground: '#FFFFFF',
  sidebarPrimary: '#F4B400',
  sidebarPrimaryForeground: '#0A0A0A',
  sidebarAccent: '#1A1A1A',
  sidebarAccentForeground: '#F4B400',
  sidebarBorder: 'rgb(255 255 255 / 0.12)',
  sidebarRing: '#F4B400',
  tableHeader: '#F4F4F4',
  tableBorder: '#E5E5E5',
  chart1: '#F4B400',
  chart2: '#0A0A0A',
  chart3: '#6B7280',
  chart4: '#2563EB',
  chart5: '#059669',
  toneGold: '#FEF3C7',
  toneGoldForeground: '#1C1917',
  toneMint: '#D1FAE5',
  toneMintForeground: '#064E3B',
  toneLavender: '#EDE9FE',
  toneLavenderForeground: '#1A1625',
  toneInk: '#0A0A0A',
  toneInkForeground: '#FFFFFF',
};

export const customerTheme: PortalThemeDefinition = {
  id: 'customer',
  name: 'Customer',
  description: 'Public yellow/black/white marketing and booking theme.',
  colors: customerLight,
};
